import { useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { Card } from "@/components/WorkspaceUI";
import { DialogSection, EntityDialog } from "@/components/EntityDialog";
import { Button } from "@/components/ui/button";
import {
  activityJobsQueryKey,
  activityUploadsQueryKey,
  activityWorkflowStageQueryKey,
  projectInterpretationsQueryKey,
  projectOverviewQueryKey,
  qualitativeCodingReviewQueryKey,
  useActivityJobsQuery,
  useApproveQualitativeCodingReviewMutation,
  useGenerateQualitativeCodingReviewMutation,
  useJobQuery,
  useQualitativeCodingReviewQuery,
  workspaceQueryKey,
} from "@/hooks/useWorkspaceQueries";
import {
  ApiError,
  type QualitativeCodingReviewColumnDecisionInput,
  type QualitativeCodingReviewFindingRecord,
} from "@/services/apiClient";

const ACTIVE_JOB_STATUSES = [
  "queued",
  "processing",
  "awaiting_privacy_review",
  "transforming",
];
const TERMINAL_JOB_STATUSES = ["completed", "failed", "cancelled"];

function readFindingsSummary(
  review: { findings: Record<string, unknown> } | null | undefined,
): QualitativeCodingReviewFindingRecord[] {
  const summary = review?.findings?.summary;
  if (!Array.isArray(summary)) {
    return [];
  }
  return summary.filter(
    (finding): finding is QualitativeCodingReviewFindingRecord =>
      Boolean(finding) && typeof finding === "object",
  );
}

function countAssignedCodes(
  finding: QualitativeCodingReviewFindingRecord,
): number {
  return finding.proposedAssignments.filter(
    (assignment) => assignment.assignedCode !== null,
  ).length;
}

export function QualitativeCodingReviewDialog({
  open,
  onOpenChange,
  uploadMetadataId,
  activityId,
  projectId,
  organizationId,
  activityName,
  originalFileName,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  uploadMetadataId: string | undefined;
  activityId: string;
  projectId: string;
  organizationId: string;
  activityName?: string;
  originalFileName?: string;
}) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [decisionByFindingKey, setDecisionByFindingKey] = useState<
    Record<string, QualitativeCodingReviewColumnDecisionInput["decision"]>
  >({});
  const [autoGeneratedUploadId, setAutoGeneratedUploadId] = useState<
    string | null
  >(null);
  const [handledTerminalJobId, setHandledTerminalJobId] = useState<
    string | null
  >(null);

  const reviewQuery = useQualitativeCodingReviewQuery(uploadMetadataId, open);
  const review = reviewQuery.data;
  const findings = readFindingsSummary(review);
  const generateReviewMutation = useGenerateQualitativeCodingReviewMutation();
  const approveReviewMutation = useApproveQualitativeCodingReviewMutation(
    activityId,
    projectId,
    organizationId,
  );

  // Re-derives the latest qualitative_coding_review job for this upload from
  // the server on every dialog open, rather than only tracking a job id this
  // component instance itself created — a job created in an earlier
  // session/mount (e.g. before the page was reloaded) is found the same way
  // a job created just now would be, so a stuck job stays trackable across a
  // reload instead of becoming invisible to this dialog.
  const activityJobsQuery = useActivityJobsQuery(activityId, open);
  const latestReviewJob = (activityJobsQuery.data ?? [])
    .filter(
      (job) =>
        job.uploadMetadataId === uploadMetadataId &&
        job.jobType === "qualitative_coding_review",
    )
    .sort(
      (left, right) =>
        new Date(right.createdAt).getTime() -
        new Date(left.createdAt).getTime(),
    )[0];
  const liveReviewJobQuery = useJobQuery(
    latestReviewJob?.id,
    Boolean(latestReviewJob?.id),
  );
  const trackedJob = liveReviewJobQuery.data ?? latestReviewJob;
  const hasActiveReviewJob = Boolean(
    trackedJob && ACTIVE_JOB_STATUSES.includes(trackedJob.status),
  );

  useEffect(() => {
    if (!open) {
      setDecisionByFindingKey({});
      setAutoGeneratedUploadId(null);
      setHandledTerminalJobId(null);
      return;
    }

    const nextDecisions = Object.fromEntries(
      (review?.decisions?.columnDecisions ?? []).map((decision) => [
        decision.findingKey,
        decision.decision,
      ]),
    );
    setDecisionByFindingKey(nextDecisions);
  }, [open, review]);

  function triggerGenerate() {
    if (!uploadMetadataId) {
      return;
    }

    generateReviewMutation.mutate(uploadMetadataId, {
      onSuccess: () => {
        void queryClient.invalidateQueries({
          queryKey: activityJobsQueryKey(activityId),
        });
      },
      onError: (error) => {
        // The backend now rejects a second generate() call for an upload
        // that already has a review (qualitative_coding_review_already_exists)
        // rather than silently regenerating and wiping approval progress —
        // see QualitativeCodingReviewService.assertReadyToGenerate. Hitting
        // that here means this auto-trigger raced a prior call for the same
        // upload; that's an expected, harmless outcome now that the backend
        // guarantees it can't overwrite anything, not a real failure, so
        // just pick up the existing review instead of alarming the user.
        if (
          error instanceof ApiError &&
          error.code === "qualitative_coding_review_already_exists"
        ) {
          void queryClient.invalidateQueries({
            queryKey: qualitativeCodingReviewQueryKey(uploadMetadataId),
          });
          return;
        }

        toast.error(
          error instanceof ApiError
            ? error.message
            : t(
                "projectWorkspace.interpretation.qualitativeReviewGenerateFailed",
              ),
        );
      },
    });
  }

  useEffect(() => {
    if (
      !open ||
      !uploadMetadataId ||
      reviewQuery.isLoading ||
      reviewQuery.isError ||
      review !== null ||
      // Don't auto-fire while a job is already active for this upload — it
      // would just 409 immediately (one active job per upload, enforced at
      // the database level). If it's genuinely stuck, deleting the evidence
      // cascades and clears it (uploadMetadataService.delete) — recreating
      // it here instead would just collide with the same lock.
      hasActiveReviewJob ||
      // Also wait for the jobs list itself to have resolved at least once.
      // Without this, reopening the dialog right after closing it mid-
      // generation could read hasActiveReviewJob as false purely because
      // this query hasn't fetched yet (not because no job is running),
      // firing a redundant generate call. The backend now rejects that
      // duplicate outright (see the onError handling in triggerGenerate),
      // so this is a belt-and-suspenders guard against the wasted request
      // and job-creation churn, not the source of correctness.
      activityJobsQuery.isLoading ||
      autoGeneratedUploadId === uploadMetadataId
    ) {
      return;
    }

    setAutoGeneratedUploadId(uploadMetadataId);
    triggerGenerate();
    // triggerGenerate intentionally omitted: it's redefined every render
    // but its behavior only depends on the values already listed below.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    activityJobsQuery.isLoading,
    autoGeneratedUploadId,
    hasActiveReviewJob,
    open,
    review,
    reviewQuery.isError,
    reviewQuery.isLoading,
    uploadMetadataId,
  ]);

  useEffect(() => {
    const job = trackedJob;
    if (
      !job ||
      !uploadMetadataId ||
      !TERMINAL_JOB_STATUSES.includes(job.status) ||
      handledTerminalJobId === job.id
    ) {
      return;
    }

    setHandledTerminalJobId(job.id);

    void queryClient.invalidateQueries({
      queryKey: qualitativeCodingReviewQueryKey(uploadMetadataId),
    });
    void queryClient.invalidateQueries({
      queryKey: activityJobsQueryKey(activityId),
    });
    void queryClient.invalidateQueries({
      queryKey: activityWorkflowStageQueryKey(activityId),
    });
    void queryClient.invalidateQueries({
      queryKey: activityUploadsQueryKey(activityId),
    });
    void queryClient.invalidateQueries({
      queryKey: projectOverviewQueryKey(projectId),
    });
    void queryClient.invalidateQueries({
      queryKey: projectInterpretationsQueryKey(projectId),
    });
    void queryClient.invalidateQueries({
      queryKey: workspaceQueryKey(organizationId),
    });

    if (job.status !== "completed") {
      toast.error(
        job.errorMessage ??
          t("projectWorkspace.interpretation.qualitativeReviewGenerateFailed"),
      );
    }
  }, [
    activityId,
    handledTerminalJobId,
    organizationId,
    projectId,
    queryClient,
    t,
    trackedJob,
    uploadMetadataId,
  ]);

  const isGenerating =
    generateReviewMutation.isPending ||
    hasActiveReviewJob ||
    reviewQuery.isLoading ||
    (open && review === null && autoGeneratedUploadId !== uploadMetadataId);
  const isSubmitting = approveReviewMutation.isPending;
  const isPendingReview = review?.status === "pending";
  const allDecisionsResolved = findings.every(
    (finding) => decisionByFindingKey[finding.findingKey],
  );
  const canSubmit =
    Boolean(uploadMetadataId && review && isPendingReview) &&
    (findings.length === 0 || allDecisionsResolved);

  async function handleSubmit() {
    if (!uploadMetadataId || !review || !isPendingReview) {
      return;
    }

    try {
      await approveReviewMutation.mutateAsync({
        uploadMetadataId,
        decisions: {
          columnDecisions: findings.map((finding) => ({
            findingKey: finding.findingKey,
            decision: decisionByFindingKey[finding.findingKey]!,
          })),
        },
      });
      toast.success(
        t("projectWorkspace.interpretation.qualitativeReviewApproveSuccess"),
      );
      onOpenChange(false);
    } catch (error) {
      toast.error(
        error instanceof ApiError
          ? error.message
          : t("projectWorkspace.interpretation.qualitativeReviewApproveFailed"),
      );
    }
  }

  return (
    <EntityDialog
      open={open}
      onOpenChange={onOpenChange}
      title={t("projectWorkspace.interpretation.qualitativeReviewTitle")}
      description={t(
        "projectWorkspace.interpretation.qualitativeReviewDescription",
      )}
      submitLabel={
        isSubmitting
          ? t("projectWorkspace.interpretation.qualitativeReviewApproving")
          : t("projectWorkspace.interpretation.qualitativeReviewApprove")
      }
      cancelLabel={t("common.close")}
      isSubmitting={isSubmitting}
      submitDisabled={!canSubmit}
      onSubmit={(event) => {
        event.preventDefault();
        void handleSubmit();
      }}
    >
      {reviewQuery.isError ? (
        <Card className="p-5">
          <div className="text-sm font-semibold text-foreground">
            {t(
              "projectWorkspace.interpretation.qualitativeReviewUnavailableTitle",
            )}
          </div>
          <p className="mt-1 text-sm leading-6 text-muted-foreground">
            {t(
              "projectWorkspace.interpretation.qualitativeReviewUnavailableDescription",
            )}
          </p>
        </Card>
      ) : isGenerating ? (
        <p className="text-sm text-muted-foreground">
          {t("projectWorkspace.interpretation.loadingQualitativeReview")}
        </p>
      ) : !review ? (
        <p className="text-sm text-muted-foreground">
          {t("projectWorkspace.interpretation.loadingQualitativeReview")}
        </p>
      ) : (
        <>
          <DialogSection
            title={t("projectWorkspace.interpretation.reviewFile")}
          >
            <div className="grid gap-3 md:grid-cols-2">
              <MetaCard
                label={t("projectWorkspace.interpretation.reviewActivity")}
                value={activityName ?? "—"}
              />
              <MetaCard
                label={t("projectWorkspace.interpretation.reviewFile")}
                value={originalFileName ?? uploadMetadataId ?? "—"}
              />
            </div>
          </DialogSection>

          {findings.length === 0 ? (
            <Card className="p-5">
              <div className="text-sm font-semibold text-foreground">
                {t(
                  "projectWorkspace.interpretation.qualitativeReviewNoFindingsTitle",
                )}
              </div>
              <p className="mt-1 text-sm leading-6 text-muted-foreground">
                {t(
                  "projectWorkspace.interpretation.qualitativeReviewNoFindingsDescription",
                )}
              </p>
            </Card>
          ) : (
            <DialogSection
              title={t(
                "projectWorkspace.interpretation.qualitativeReviewFindings",
              )}
            >
              <div className="space-y-4">
                {findings.map((finding) => {
                  const selectedDecision =
                    decisionByFindingKey[finding.findingKey] ?? null;

                  return (
                    <Card key={finding.findingKey} className="p-5">
                      <div className="flex flex-wrap items-start justify-between gap-3">
                        <div>
                          <div className="text-sm font-semibold text-foreground">
                            {finding.tableName} · {finding.textColumnName}
                          </div>
                          <p className="mt-1 text-sm leading-6 text-muted-foreground">
                            {t(
                              "projectWorkspace.interpretation.qualitativeReviewFindingMeta",
                              {
                                rows: finding.rowCount,
                                codedRows: countAssignedCodes(finding),
                                syntheticColumnName:
                                  finding.syntheticCodeColumnName,
                              },
                            )}
                          </p>
                        </div>
                        {finding.sourceCodebookOriginalFileName ? (
                          <div className="text-xs leading-5 text-muted-foreground">
                            {t(
                              "projectWorkspace.interpretation.qualitativeReviewCodebook",
                              {
                                fileName:
                                  finding.sourceCodebookOriginalFileName,
                              },
                            )}
                          </div>
                        ) : null}
                      </div>

                      <div className="mt-4 grid gap-3 md:grid-cols-2">
                        {finding.proposedCodes.map((code) => (
                          <div
                            key={`${finding.findingKey}_${code.code}`}
                            className="rounded-[12px] border border-border/70 bg-background/70 p-4"
                          >
                            <div className="text-sm font-semibold text-foreground">
                              {code.label}
                            </div>
                            <div className="mt-1 text-xs font-medium uppercase tracking-[0.08em] text-muted-foreground">
                              {code.code}
                            </div>
                            <p className="mt-2 text-sm leading-6 text-muted-foreground">
                              {code.description}
                            </p>
                          </div>
                        ))}
                      </div>

                      {finding.sampleExcerpts.length > 0 ? (
                        <div className="mt-4 space-y-2">
                          <div className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">
                            {t(
                              "projectWorkspace.interpretation.qualitativeReviewExcerpts",
                            )}
                          </div>
                          {finding.sampleExcerpts.map((excerpt, index) => (
                            <blockquote
                              key={`${finding.findingKey}_${index + 1}`}
                              className="rounded-[12px] border border-border/70 bg-background/70 px-4 py-3 text-sm leading-6 text-foreground"
                            >
                              “{excerpt}”
                            </blockquote>
                          ))}
                        </div>
                      ) : null}

                      <div className="mt-4 flex flex-wrap gap-2">
                        <Button
                          type="button"
                          size="sm"
                          variant={
                            selectedDecision === "approve_as_proposed"
                              ? "default"
                              : "outline"
                          }
                          onClick={() =>
                            setDecisionByFindingKey((current) => ({
                              ...current,
                              [finding.findingKey]: "approve_as_proposed",
                            }))
                          }
                        >
                          {t(
                            "projectWorkspace.interpretation.qualitativeReviewDecisionApprove",
                          )}
                        </Button>
                        <Button
                          type="button"
                          size="sm"
                          variant={
                            selectedDecision === "reject_for_now"
                              ? "default"
                              : "outline"
                          }
                          onClick={() =>
                            setDecisionByFindingKey((current) => ({
                              ...current,
                              [finding.findingKey]: "reject_for_now",
                            }))
                          }
                        >
                          {t(
                            "projectWorkspace.interpretation.qualitativeReviewDecisionReject",
                          )}
                        </Button>
                      </div>
                    </Card>
                  );
                })}
              </div>
            </DialogSection>
          )}
        </>
      )}
    </EntityDialog>
  );
}

function MetaCard({ label, value }: { label: string; value: string }) {
  return (
    <Card className="p-4">
      <div className="text-xs font-medium uppercase tracking-[0.08em] text-muted-foreground">
        {label}
      </div>
      <div className="mt-2 text-sm font-semibold text-foreground">{value}</div>
    </Card>
  );
}
