/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as OrganizationsOrganizationIdRouteRouteImport } from './routes/organizations/$organizationId/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdInsightsRouteImport } from './routes/projects/$projectId/insights'
import { Route as ProjectsProjectIdAnalyticsRouteImport } from './routes/projects/$projectId/analytics'
import { Route as ProjectsProjectIdActivitiesActivityIdUploadRouteImport } from './routes/projects/$projectId/activities/$activityId/upload'
import { Route as ProjectsProjectIdActivitiesActivityIdSettingsRouteImport } from './routes/projects/$projectId/activities/$activityId/settings'
import { Route as ProjectsProjectIdActivitiesActivityIdSchemaRouteImport } from './routes/projects/$projectId/activities/$activityId/schema'
import { Route as ProjectsProjectIdActivitiesActivityIdProcessingRouteImport } from './routes/projects/$projectId/activities/$activityId/processing'
import { Route as ProjectsProjectIdActivitiesActivityIdOverviewRouteImport } from './routes/projects/$projectId/activities/$activityId/overview'
import { Route as ProjectsProjectIdActivitiesActivityIdInsightsRouteImport } from './routes/projects/$projectId/activities/$activityId/insights'
import { Route as ProjectsProjectIdActivitiesActivityIdDataReviewRouteImport } from './routes/projects/$projectId/activities/$activityId/data-review'
import { Route as ProjectsProjectIdActivitiesActivityIdBriefRouteImport } from './routes/projects/$projectId/activities/$activityId/brief'
import { Route as ProjectsProjectIdActivitiesActivityIdAnalyticsRouteImport } from './routes/projects/$projectId/activities/$activityId/analytics'
import { Route as ProjectsProjectIdActivitiesActivityIdAnalysisRouteImport } from './routes/projects/$projectId/activities/$activityId/analysis'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdRouteRoute =
  OrganizationsOrganizationIdRouteRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdInsightsRoute =
  ProjectsProjectIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdAnalyticsRoute =
  ProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdUploadRoute =
  ProjectsProjectIdActivitiesActivityIdUploadRouteImport.update({
    id: '/activities/$activityId/upload',
    path: '/activities/$activityId/upload',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdSettingsRoute =
  ProjectsProjectIdActivitiesActivityIdSettingsRouteImport.update({
    id: '/activities/$activityId/settings',
    path: '/activities/$activityId/settings',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdSchemaRoute =
  ProjectsProjectIdActivitiesActivityIdSchemaRouteImport.update({
    id: '/activities/$activityId/schema',
    path: '/activities/$activityId/schema',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdProcessingRoute =
  ProjectsProjectIdActivitiesActivityIdProcessingRouteImport.update({
    id: '/activities/$activityId/processing',
    path: '/activities/$activityId/processing',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdOverviewRoute =
  ProjectsProjectIdActivitiesActivityIdOverviewRouteImport.update({
    id: '/activities/$activityId/overview',
    path: '/activities/$activityId/overview',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdInsightsRoute =
  ProjectsProjectIdActivitiesActivityIdInsightsRouteImport.update({
    id: '/activities/$activityId/insights',
    path: '/activities/$activityId/insights',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdDataReviewRoute =
  ProjectsProjectIdActivitiesActivityIdDataReviewRouteImport.update({
    id: '/activities/$activityId/data-review',
    path: '/activities/$activityId/data-review',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdBriefRoute =
  ProjectsProjectIdActivitiesActivityIdBriefRouteImport.update({
    id: '/activities/$activityId/brief',
    path: '/activities/$activityId/brief',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdAnalyticsRoute =
  ProjectsProjectIdActivitiesActivityIdAnalyticsRouteImport.update({
    id: '/activities/$activityId/analytics',
    path: '/activities/$activityId/analytics',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdActivitiesActivityIdAnalysisRoute =
  ProjectsProjectIdActivitiesActivityIdAnalysisRouteImport.update({
    id: '/activities/$activityId/analysis',
    path: '/activities/$activityId/analysis',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/insights': typeof ProjectsProjectIdInsightsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/activities/$activityId/analysis': typeof ProjectsProjectIdActivitiesActivityIdAnalysisRoute
  '/projects/$projectId/activities/$activityId/analytics': typeof ProjectsProjectIdActivitiesActivityIdAnalyticsRoute
  '/projects/$projectId/activities/$activityId/brief': typeof ProjectsProjectIdActivitiesActivityIdBriefRoute
  '/projects/$projectId/activities/$activityId/data-review': typeof ProjectsProjectIdActivitiesActivityIdDataReviewRoute
  '/projects/$projectId/activities/$activityId/insights': typeof ProjectsProjectIdActivitiesActivityIdInsightsRoute
  '/projects/$projectId/activities/$activityId/overview': typeof ProjectsProjectIdActivitiesActivityIdOverviewRoute
  '/projects/$projectId/activities/$activityId/processing': typeof ProjectsProjectIdActivitiesActivityIdProcessingRoute
  '/projects/$projectId/activities/$activityId/schema': typeof ProjectsProjectIdActivitiesActivityIdSchemaRoute
  '/projects/$projectId/activities/$activityId/settings': typeof ProjectsProjectIdActivitiesActivityIdSettingsRoute
  '/projects/$projectId/activities/$activityId/upload': typeof ProjectsProjectIdActivitiesActivityIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/insights': typeof ProjectsProjectIdInsightsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/activities/$activityId/analysis': typeof ProjectsProjectIdActivitiesActivityIdAnalysisRoute
  '/projects/$projectId/activities/$activityId/analytics': typeof ProjectsProjectIdActivitiesActivityIdAnalyticsRoute
  '/projects/$projectId/activities/$activityId/brief': typeof ProjectsProjectIdActivitiesActivityIdBriefRoute
  '/projects/$projectId/activities/$activityId/data-review': typeof ProjectsProjectIdActivitiesActivityIdDataReviewRoute
  '/projects/$projectId/activities/$activityId/insights': typeof ProjectsProjectIdActivitiesActivityIdInsightsRoute
  '/projects/$projectId/activities/$activityId/overview': typeof ProjectsProjectIdActivitiesActivityIdOverviewRoute
  '/projects/$projectId/activities/$activityId/processing': typeof ProjectsProjectIdActivitiesActivityIdProcessingRoute
  '/projects/$projectId/activities/$activityId/schema': typeof ProjectsProjectIdActivitiesActivityIdSchemaRoute
  '/projects/$projectId/activities/$activityId/settings': typeof ProjectsProjectIdActivitiesActivityIdSettingsRoute
  '/projects/$projectId/activities/$activityId/upload': typeof ProjectsProjectIdActivitiesActivityIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/insights': typeof ProjectsProjectIdInsightsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/activities/$activityId/analysis': typeof ProjectsProjectIdActivitiesActivityIdAnalysisRoute
  '/projects/$projectId/activities/$activityId/analytics': typeof ProjectsProjectIdActivitiesActivityIdAnalyticsRoute
  '/projects/$projectId/activities/$activityId/brief': typeof ProjectsProjectIdActivitiesActivityIdBriefRoute
  '/projects/$projectId/activities/$activityId/data-review': typeof ProjectsProjectIdActivitiesActivityIdDataReviewRoute
  '/projects/$projectId/activities/$activityId/insights': typeof ProjectsProjectIdActivitiesActivityIdInsightsRoute
  '/projects/$projectId/activities/$activityId/overview': typeof ProjectsProjectIdActivitiesActivityIdOverviewRoute
  '/projects/$projectId/activities/$activityId/processing': typeof ProjectsProjectIdActivitiesActivityIdProcessingRoute
  '/projects/$projectId/activities/$activityId/schema': typeof ProjectsProjectIdActivitiesActivityIdSchemaRoute
  '/projects/$projectId/activities/$activityId/settings': typeof ProjectsProjectIdActivitiesActivityIdSettingsRoute
  '/projects/$projectId/activities/$activityId/upload': typeof ProjectsProjectIdActivitiesActivityIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/organizations/$organizationId'
    | '/projects/$projectId'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/insights'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/activities/$activityId/analysis'
    | '/projects/$projectId/activities/$activityId/analytics'
    | '/projects/$projectId/activities/$activityId/brief'
    | '/projects/$projectId/activities/$activityId/data-review'
    | '/projects/$projectId/activities/$activityId/insights'
    | '/projects/$projectId/activities/$activityId/overview'
    | '/projects/$projectId/activities/$activityId/processing'
    | '/projects/$projectId/activities/$activityId/schema'
    | '/projects/$projectId/activities/$activityId/settings'
    | '/projects/$projectId/activities/$activityId/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/organizations/$organizationId'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/insights'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/activities/$activityId/analysis'
    | '/projects/$projectId/activities/$activityId/analytics'
    | '/projects/$projectId/activities/$activityId/brief'
    | '/projects/$projectId/activities/$activityId/data-review'
    | '/projects/$projectId/activities/$activityId/insights'
    | '/projects/$projectId/activities/$activityId/overview'
    | '/projects/$projectId/activities/$activityId/processing'
    | '/projects/$projectId/activities/$activityId/schema'
    | '/projects/$projectId/activities/$activityId/settings'
    | '/projects/$projectId/activities/$activityId/upload'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/organizations/$organizationId'
    | '/projects/$projectId'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/insights'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/activities/$activityId/analysis'
    | '/projects/$projectId/activities/$activityId/analytics'
    | '/projects/$projectId/activities/$activityId/brief'
    | '/projects/$projectId/activities/$activityId/data-review'
    | '/projects/$projectId/activities/$activityId/insights'
    | '/projects/$projectId/activities/$activityId/overview'
    | '/projects/$projectId/activities/$activityId/processing'
    | '/projects/$projectId/activities/$activityId/schema'
    | '/projects/$projectId/activities/$activityId/settings'
    | '/projects/$projectId/activities/$activityId/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OrganizationsOrganizationIdRouteRoute: typeof OrganizationsOrganizationIdRouteRoute
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/insights': {
      id: '/projects/$projectId/insights'
      path: '/insights'
      fullPath: '/projects/$projectId/insights'
      preLoaderRoute: typeof ProjectsProjectIdInsightsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/analytics': {
      id: '/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/projects/$projectId/analytics'
      preLoaderRoute: typeof ProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/upload': {
      id: '/projects/$projectId/activities/$activityId/upload'
      path: '/activities/$activityId/upload'
      fullPath: '/projects/$projectId/activities/$activityId/upload'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdUploadRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/settings': {
      id: '/projects/$projectId/activities/$activityId/settings'
      path: '/activities/$activityId/settings'
      fullPath: '/projects/$projectId/activities/$activityId/settings'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/schema': {
      id: '/projects/$projectId/activities/$activityId/schema'
      path: '/activities/$activityId/schema'
      fullPath: '/projects/$projectId/activities/$activityId/schema'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdSchemaRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/processing': {
      id: '/projects/$projectId/activities/$activityId/processing'
      path: '/activities/$activityId/processing'
      fullPath: '/projects/$projectId/activities/$activityId/processing'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdProcessingRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/overview': {
      id: '/projects/$projectId/activities/$activityId/overview'
      path: '/activities/$activityId/overview'
      fullPath: '/projects/$projectId/activities/$activityId/overview'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdOverviewRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/insights': {
      id: '/projects/$projectId/activities/$activityId/insights'
      path: '/activities/$activityId/insights'
      fullPath: '/projects/$projectId/activities/$activityId/insights'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdInsightsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/data-review': {
      id: '/projects/$projectId/activities/$activityId/data-review'
      path: '/activities/$activityId/data-review'
      fullPath: '/projects/$projectId/activities/$activityId/data-review'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdDataReviewRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/brief': {
      id: '/projects/$projectId/activities/$activityId/brief'
      path: '/activities/$activityId/brief'
      fullPath: '/projects/$projectId/activities/$activityId/brief'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdBriefRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/analytics': {
      id: '/projects/$projectId/activities/$activityId/analytics'
      path: '/activities/$activityId/analytics'
      fullPath: '/projects/$projectId/activities/$activityId/analytics'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdAnalyticsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activities/$activityId/analysis': {
      id: '/projects/$projectId/activities/$activityId/analysis'
      path: '/activities/$activityId/analysis'
      fullPath: '/projects/$projectId/activities/$activityId/analysis'
      preLoaderRoute: typeof ProjectsProjectIdActivitiesActivityIdAnalysisRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
  }
}

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdAnalyticsRoute: typeof ProjectsProjectIdAnalyticsRoute
  ProjectsProjectIdInsightsRoute: typeof ProjectsProjectIdInsightsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdActivitiesActivityIdAnalysisRoute: typeof ProjectsProjectIdActivitiesActivityIdAnalysisRoute
  ProjectsProjectIdActivitiesActivityIdAnalyticsRoute: typeof ProjectsProjectIdActivitiesActivityIdAnalyticsRoute
  ProjectsProjectIdActivitiesActivityIdBriefRoute: typeof ProjectsProjectIdActivitiesActivityIdBriefRoute
  ProjectsProjectIdActivitiesActivityIdDataReviewRoute: typeof ProjectsProjectIdActivitiesActivityIdDataReviewRoute
  ProjectsProjectIdActivitiesActivityIdInsightsRoute: typeof ProjectsProjectIdActivitiesActivityIdInsightsRoute
  ProjectsProjectIdActivitiesActivityIdOverviewRoute: typeof ProjectsProjectIdActivitiesActivityIdOverviewRoute
  ProjectsProjectIdActivitiesActivityIdProcessingRoute: typeof ProjectsProjectIdActivitiesActivityIdProcessingRoute
  ProjectsProjectIdActivitiesActivityIdSchemaRoute: typeof ProjectsProjectIdActivitiesActivityIdSchemaRoute
  ProjectsProjectIdActivitiesActivityIdSettingsRoute: typeof ProjectsProjectIdActivitiesActivityIdSettingsRoute
  ProjectsProjectIdActivitiesActivityIdUploadRoute: typeof ProjectsProjectIdActivitiesActivityIdUploadRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdAnalyticsRoute: ProjectsProjectIdAnalyticsRoute,
    ProjectsProjectIdInsightsRoute: ProjectsProjectIdInsightsRoute,
    ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
    ProjectsProjectIdActivitiesActivityIdAnalysisRoute:
      ProjectsProjectIdActivitiesActivityIdAnalysisRoute,
    ProjectsProjectIdActivitiesActivityIdAnalyticsRoute:
      ProjectsProjectIdActivitiesActivityIdAnalyticsRoute,
    ProjectsProjectIdActivitiesActivityIdBriefRoute:
      ProjectsProjectIdActivitiesActivityIdBriefRoute,
    ProjectsProjectIdActivitiesActivityIdDataReviewRoute:
      ProjectsProjectIdActivitiesActivityIdDataReviewRoute,
    ProjectsProjectIdActivitiesActivityIdInsightsRoute:
      ProjectsProjectIdActivitiesActivityIdInsightsRoute,
    ProjectsProjectIdActivitiesActivityIdOverviewRoute:
      ProjectsProjectIdActivitiesActivityIdOverviewRoute,
    ProjectsProjectIdActivitiesActivityIdProcessingRoute:
      ProjectsProjectIdActivitiesActivityIdProcessingRoute,
    ProjectsProjectIdActivitiesActivityIdSchemaRoute:
      ProjectsProjectIdActivitiesActivityIdSchemaRoute,
    ProjectsProjectIdActivitiesActivityIdSettingsRoute:
      ProjectsProjectIdActivitiesActivityIdSettingsRoute,
    ProjectsProjectIdActivitiesActivityIdUploadRoute:
      ProjectsProjectIdActivitiesActivityIdUploadRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OrganizationsOrganizationIdRouteRoute: OrganizationsOrganizationIdRouteRoute,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
